steps:
- name: Daten sammeln
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python ingest.py
- name: Vorverarbeitung
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python prepare.py