steps:
- name: Daten sammeln
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python ingest.py
- name: Exploration
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python explore.py
- name: Vorverarbeitung
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python prepare.py
- name: Training
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python train.py