steps:
- name: Daten sammeln
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python ingest.py
- name: Daten bereinigen
    docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python clean.py
- name: Vorverarbeitung
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python prepare.py
- name: Training
  docker:
    buildConfiguration:
        context: ./dockerfiles/
        dockerfile: run.dockerfile
    command: python train.py